--- 
- 
  become: true
  hosts: all
  tasks: 
    - 
      ignore_errors: true
      name: "stop previous version docker"
      shell: "docker stop devops"
    - 
      ignore_errors: true
      name: "remove stopped container"
      shell: "docker rm -f devops"
    - 
      ignore_errors: true
      name: "remove docker images"
      shell: "docker image rm -f monicakoli/devops"
    - 
      name: "create docker image"
      shell: "docker run -d --name devops -p 8090:8080 monicakoli/devops"
